_wandb:
    value:
        cli_version: 0.21.3
        code_path: code/test_wandb_gha.py
        e:
            y0aj82eyanw71ssnudye4ljs7a2atbpq:
                apple:
                    ecpuCores: 4
                    gpuCores: 20
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 10
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "8589934592"
                codePath: test_wandb_gha.py
                codePathLocal: test_wandb_gha.py
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "494384795648"
                        used: "312704983040"
                email: rsong@wandb.com
                executable: /Users/rsong/woven-toyota/wandb-gha-test/venv/bin/python
                git:
                    commit: 5213a1de545a0e13b951a7365c92af84bcc8f996
                    remote: https://github.com/rsong9527/wandb-gha-test.git
                host: Richard-Song-FMK9FVTDKM
                memory:
                    total: "25769803776"
                os: macOS-15.6.1-arm64-arm-64bit-Mach-O
                program: /Users/rsong/woven-toyota/wandb-gha-test/test_wandb_gha.py
                python: CPython 3.13.3
                root: /Users/rsong/woven-toyota/wandb-gha-test
                startedAt: "2025-09-11T04:15:11.865639Z"
                writerId: y0aj82eyanw71ssnudye4ljs7a2atbpq
        m: []
        python_version: 3.13.3
        t:
            "3":
                - 2
                - 13
                - 15
            "4": 3.13.3
            "5": 0.21.3
            "12": 0.21.3
            "13": darwin-arm64
