name: Manual Debug Test

on:
  workflow_dispatch:

jobs:
  manual-debug:
    name: "Manual W&B Debug"
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install wandb
      run: |
        pip install wandb
        
    - name: Environment Info
      run: |
        echo "=== Environment ==="
        python --version
        wandb --version
        env | grep -E "(CI|GITHUB)" | sort
        
    - name: Test wandb verify
      env:
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        WANDB_BASE_URL: https://staging-aws.wandb.io
      run: |
        echo "=== wandb verify test ==="
        echo "Base URL: $WANDB_BASE_URL"
        wandb verify || true
        
    - name: Test basic wandb
      env:
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        WANDB_BASE_URL: https://staging-aws.wandb.io
      run: |
        echo "=== Basic wandb test ==="
        python -c "
        import wandb
        print('Initializing run...')
        run = wandb.init(project='manual-debug', name='test-run')
        print('Run URL:', run.url)
        wandb.log({'test': 1})
        wandb.finish()
        print('Test completed successfully!')
        "
