name: W&B Verify

on:
  workflow_dispatch:   # 手动触发

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install wandb
        run: |
          python -m pip install --upgrade pip
          python -m pip install wandb

      - name: Run wandb verify
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
          WANDB_BASE_URL: https://staging-aws.wandb.io   # 或 woven 的 base
        run: |
          wandb --version
          wandb verify
